### ISSUE TITLE
[Week01] <!DOCTYPE html>

### ISSUE THREAD

**Issue by zigsong** [woowacourse-fe-study/havruta-frontend#2]
우리가 매일같이 사용하는 `DOCTYPE`, 무엇인지 알고 쓰셨나요? 🤔 
이번 기회에 같이 알아보도록 합시다! 

아래 참고 링크를 읽고, 페어와 스터디 시작 후 간단하게 워밍업 주제로 다뤄보아요 👾
[참고 링크 - doctype은 무엇을 하나요](https://github.com/yangshun/front-end-interview-handbook/blob/master/contents/kr/html-questions.md#doctype은-무엇을-하나요)

**Comment by 365kim** [comment]
`워밍업 질문`은 서로 나눴던 이야기 중 공유하고 싶은 내용이 있다면 선택적으로 코멘트 달아주세요! 🦕🦕

**Comment by 365kim** [comment]
![image](https://user-images.githubusercontent.com/60066472/112717038-4cd10880-8f2d-11eb-81d0-09ef37a76b14.png)
### [링크](https://www.youtube.com/watch?v=EgT5520Ztek)

**Comment by iborymagic** [comment]
비슷한 느낌으로다가 MIME도 한 번 보고 가십쇼
[링크](https://www.youtube.com/watch?v=FBkZ2TJZZUY&t=1s)
